name: Run Bash Script

on: [push]

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run show-date script
        run: bash ./scripts/show-date.sh
