name: Run Bash and Python scripts

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Run Bash script to show date/time in Israel
      run: bash ./scripts/show-date.sh

    - name: Run Python script to check palindrome
      run: python3 ./scripts/check_palindrome.py
